package ua.com.paradine.core.business;

import org.mapstruct.Mapper;
import ua.com.paradine.domain.PopularTime;
import ua.com.paradine.domain.Restaurant;

@Mapper(componentModel = "spring", uses = {})
/*
  Since JPA Entities are auto-generated by JHipster (and likely to change in future), <br/>
  I've decided to create a separate set of symmetrical value objects to use in business operations. <br/>
  This mapper converts DAO objects (JPA entities) into value objects. <br/>
  <br/>
  Note that the data fields in value objects are *not* the same as in JPA Entities. <br/>
 */
public interface RestaurantMapperBusiness {

    RestaurantVO dbEntityToValueObject(Restaurant restaurant);

    PopularTimeVO dbEntityToValueObject(PopularTime popularTime);
}
