package ua.com.paradine.core.business;

import java.util.Set;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;
import ua.com.paradine.core.business.vo.ClassifiedRestaurantVO;
import ua.com.paradine.core.business.vo.HourlyClassifier;
import ua.com.paradine.core.business.vo.PopularTimeVO;
import ua.com.paradine.core.business.vo.RestaurantVO;
import ua.com.paradine.domain.PopularTime;
import ua.com.paradine.domain.Restaurant;

@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
/*
  Since JPA Entities are auto-generated by JHipster (and likely to change in future), <br/>
  I've decided to create a separate set of symmetrical value objects to use in business operations. <br/>
  This mapper converts DAO objects (JPA entities) into value objects. <br/>
  <br/>
  Note that the data fields in value objects are *not* the same as in JPA Entities. <br/>
 */
public interface RestaurantMapperBusiness {

    RestaurantVO dbEntityToValueObject(Restaurant restaurant);

    ClassifiedRestaurantVO convertToSafety(RestaurantVO restaurant, Set<HourlyClassifier> classifiersToday,
        Set<HourlyClassifier> classifiersTomorrow);

//    default Set<ClassifiedRestaurantVO> convertToSafety(Set<RestaurantVO> restaurants, SafetyMarker marker) {
//        return restaurants.stream().map(r -> convertToSafety(r, marker)).collect(Collectors.toSet());
//    }

    PopularTimeVO dbEntityToValueObject(PopularTime popularTime);
    Set<PopularTimeVO> dbEntityToValueObject(Set<PopularTime> popularTime);
}
